[tool.poetry]
name = "main"
version = "0.0.1"
description = ""
authors = ["Martin Courtois <martin.courtois@protonmail.com>"]

[tool.poetry.dependencies]
python = "^3.8"

[tool.poetry.dev-dependencies]
pytest = "^6.1.2"
tox = "^3.20.1"

[tool.poetry.scripts]
main = "main:main"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"